before_script:
  - ssh-keyscan -t rsa,dsa,ecdsa git.intranet.struktur.de gitserver.intranet.struktur.de github.com > /etc/ssh/ssh_known_hosts

mirror-master:
  stage: deploy
  only:
    - master
  script:
    - git remote add github git@github.com:fancycode/mirror-test.git || true
    - git fetch github
    - git push github refs/heads/master

mirror-tags:
  stage: deploy
  only:
    - tags
  script:
    - git remote add github git@github.com:fancycode/mirror-test.git || true
    - git fetch github
    - git push --tags github
