before_script:
  - ssh-keyscan -t rsa,dsa,ecdsa github.com $ADDITIONAL_GIT_SERVERS > /etc/ssh/ssh_known_hosts

mirror-master:
  stage: deploy
  only:
    - master
  script:
    - git remote add github git@github.com:fancycode/mirror-test.git || true
    - git fetch github
    - git push --progress github HEAD:master

mirror-tags:
  stage: deploy
  only:
    - tags
  script:
    - git remote add github git@github.com:fancycode/mirror-test.git || true
    - git fetch github
    - git push --progress --tags github
